/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#003b5a',
        'primary-container': '#1a5276',
        secondary: '#745a27',
        'secondary-container': '#fedb9b',
        surface: '#fbf9f6',
        'surface-container': '#efeeeb',
        'surface-container-low': '#f5f3f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-variant': '#e4e2df',
        'surface-dim': '#dbdad7',
        'surface-bright': '#fbf9f6',
        background: '#fbf9f6',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#41474e',
        'on-primary': '#ffffff',
        'on-primary-container': '#94c5ee',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#795f2b',
        'outline-variant': '#c1c7cf',
        outline: '#72787f',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#9bccf6',
        'primary-fixed': '#cbe6ff',
        'primary-fixed-dim': '#9bccf6',
        'secondary-fixed': '#ffdea4',
        'secondary-fixed-dim': '#e4c285',
        'tertiary-fixed': '#e8e1d8',
        'tertiary-fixed-dim': '#ccc6bd',
        tertiary: '#3a3630',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1e1b16',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      spacing: {
        'sidebar-width': '260px',
        'container-margin': '32px',
        'gutter': '20px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
      },
      borderRadius: {
        'lg': '8px',
        'xl': '12px',
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
